### ISSUE TITLE
FLEXall not compatible with libFLEX v4.4.0 on iPad Pro 12.9

### ISSUE THREAD

**Issue by yur1xpp** [DGh0st/FLEXall#7]
I'm not really sure what the issue is, but upgrading to libFLEX 4.4.0 broke FLEXall on iPad Pro 12.9 (iPadOS 13.5, unc0ver). Activation via three finger and long pressing on the status bar didn't activate it. Downgraded to v4.3.0 and it worked as expected. However, on an iPhone, v4.4.0 is fully working. Do let me know how I can provide more details on this. Thanks!

**Comment by DGh0st** [comment]
If its working fine on iPhone, then I don't think its a compatibility issue unless libFLEX changed something that only impacts iPads (doubt it).

Have you tried reinstalling FLEXall 0.0.1-21 and libFLEX 4.4.0?

If that doesn't work, something interesting to narrow down the root cause would be to try different combinations of FLEXall and libFLEX.

| FLEXall | libFLEX | Activation |
| -------- | ------- | ----------- |
| 0.0.1-21 | 4.4.0 | Does nothing |
| 0.0.1-21 | 4.3.0 | Activates FLEX |
| 0.0.1-20 | 4.4.0 | What does this do? |
| 0.0.1-20 | 4.3.0 | (should activate FLEX like before I hope) |

**Comment by yur1xpp** [comment]
> Have you tried reinstalling FLEXall 0.0.1-21 and libFLEX 4.4.0?

I did, unfortunately it stays the same.

These are the result that I tested, interesting to find that version 0.0.1-11 and below works with libFLEX v4.4.0. Do you have any idea about it?

FLEXall | libFLEX | Activation
-- | -- | --
0.0.1-21 | 4.4.0 | Does nothing
0.0.1-21 | 4.3.0 | Activates FLEX
0.0.1-20 | 4.4.0 | Does nothing
0.0.1-20 | 4.3.0 | Activates FLEX
<=0.0.1-11 | 4.4.0 | Activates FLEX
\>0.0.1-12 | 4.4.0 | Does nothing

**Comment by DGh0st** [comment]
Is iPad Pro 12.9 arm64e? It could be possible that libFLEX 4.4.0 doesn't have an arm64e slice. In which case this would be a libFLEX issue.

**Comment by yur1xpp** [comment]
Yep it's iPad Pro 2020, A12, and I can't believe that, you're right! With latest FLEXall and libFLEX v4.4.0, it does load in apps, but not springboard. I should close this and open new issue on libFLEX. Thank you so much for the help with this issue! :)
